-- ═══════════════════════════════════════════════════════════════════════════════════════════
--  Simulação de Incorporação — setup v1 (tabela própria; NADA do Análise Tributária Pro é tocado)
--  Rodar UMA vez no SQL Editor do Supabase, ANTES de publicar o incorporacao.html.
--  Idempotente: pode ser executado de novo sem efeito colateral.
--  Reproduzido em PostgreSQL 16.15 local com sql/testes_incorporacao_v1.sql (10/10) antes da entrega.
--
--  Desenho:
--   · atp_incorporacoes: uma linha por simulação gravada (escritório dono, incorporadora, incorporadas,
--     cópia dos dados importados, premissas e snapshot do resultado);
--   · escritorio_id preenchido por padrão com atp_meu_escritorio() — a mesma função que já isola as
--     tabelas do ATP; o cliente nunca informa o escritório;
--   · RLS em 4 políticas por comando (SELECT/INSERT/UPDATE/DELETE), com WITH CHECK explícito — a lição
--     da v7.41.1: soft-delete é incompatível com política FOR ALL que esconde a própria linha;
--   · exclusão LÓGICA por função SECURITY DEFINER atp_excluir_incorporacao(id), que confere o
--     escritório e marca excluido_em por fora da RLS (mesmo padrão de atp_excluir_dados);
--   · trilha: criado_por/atualizado_por carimbados pelo e-mail do JWT no gatilho.
-- ═══════════════════════════════════════════════════════════════════════════════════════════

create table if not exists public.atp_incorporacoes (
  id                  bigint generated by default as identity primary key,
  escritorio_id       uuid        not null default public.atp_meu_escritorio(),
  ano                 integer     not null,
  cnpj_incorporadora  text        not null check (cnpj_incorporadora ~ '^[0-9]{14}$'),
  cnpjs_incorporadas  jsonb       not null default '[]'::jsonb,
  titulo              text,
  entradas            jsonb       not null default '{}'::jsonb,   -- cópia dos dados importados (só leitura das análises)
  premissas           jsonb       not null default '{}'::jsonb,   -- janela, abatimentos confirmados, valores manuais
  snapshot            jsonb       not null default '{}'::jsonb,   -- resultado da época + versão do card + lacre do motor
  criado_em           timestamptz not null default now(),
  criado_por          text,
  atualizado_em       timestamptz,
  atualizado_por      text,
  excluido_em         timestamptz,
  excluido_por        text,
  constraint atp_incorporacoes_incorporadas_lista check (jsonb_typeof(cnpjs_incorporadas) = 'array'),
  constraint atp_incorporacoes_pelo_menos_uma      check (jsonb_array_length(cnpjs_incorporadas) >= 1)
);
create index if not exists atp_incorporacoes_escr_idx on public.atp_incorporacoes (escritorio_id, criado_em desc) where excluido_em is null;
create index if not exists atp_incorporacoes_inc_idx  on public.atp_incorporacoes (cnpj_incorporadora, ano);

comment on table public.atp_incorporacoes is 'Simulação de Incorporação — simulações gravadas (uma por cálculo salvo). Não altera atp_analises.';

-- ── trilha: quem criou / alterou / excluiu (e-mail do JWT; service_role fica sem e-mail) ──
create or replace function public.atp_inc_trilha() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_email text := coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email', null);
begin
  if tg_op = 'INSERT' then
    new.criado_em := coalesce(new.criado_em, now());
    new.criado_por := coalesce(new.criado_por, v_email);
    new.excluido_em := null; new.excluido_por := null;         -- ninguém nasce excluído
  elsif tg_op = 'UPDATE' then
    new.atualizado_em := now();
    new.atualizado_por := coalesce(v_email, new.atualizado_por);
    if new.excluido_em is not null and old.excluido_em is null then new.excluido_por := coalesce(new.excluido_por, v_email); end if;
    -- chaves imutáveis: escritório, incorporadora, ano
    new.escritorio_id := old.escritorio_id; new.cnpj_incorporadora := old.cnpj_incorporadora; new.ano := old.ano;
  end if;
  return new;
end $$;
drop trigger if exists atp_inc_trilha on public.atp_incorporacoes;
create trigger atp_inc_trilha before insert or update on public.atp_incorporacoes
  for each row execute function public.atp_inc_trilha();

-- ── RLS: 4 políticas por comando ──
alter table public.atp_incorporacoes enable row level security;
alter table public.atp_incorporacoes force row level security;   -- vale também para o dono da tabela
drop policy if exists atp_incorporacoes_sel on public.atp_incorporacoes;
drop policy if exists atp_incorporacoes_ins on public.atp_incorporacoes;
drop policy if exists atp_incorporacoes_upd on public.atp_incorporacoes;
drop policy if exists atp_incorporacoes_del on public.atp_incorporacoes;
-- (select …) escalar: a função STABLE roda uma vez por consulta, não por linha (lição de desempenho da licença)
create policy atp_incorporacoes_sel on public.atp_incorporacoes for select to authenticated
  using (escritorio_id = (select public.atp_meu_escritorio()) and excluido_em is null);
create policy atp_incorporacoes_ins on public.atp_incorporacoes for insert to authenticated
  with check (escritorio_id = (select public.atp_meu_escritorio()));
create policy atp_incorporacoes_upd on public.atp_incorporacoes for update to authenticated
  using (escritorio_id = (select public.atp_meu_escritorio()) and excluido_em is null)
  with check (escritorio_id = (select public.atp_meu_escritorio()));
create policy atp_incorporacoes_del on public.atp_incorporacoes for delete to authenticated
  using (false);                                   -- exclusão física nunca pelo cliente
grant select, insert, update on public.atp_incorporacoes to authenticated;
revoke delete on public.atp_incorporacoes from authenticated;

-- ── exclusão LÓGICA por função (SECURITY DEFINER passa por cima da RLS: por isso confere o escritório) ──
create or replace function public.atp_excluir_incorporacao(p_id bigint) returns jsonb
language plpgsql security definer set search_path = public as $$
declare v_escr uuid := public.atp_meu_escritorio();
        v_email text := coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email', null);
        v_n int;
begin
  if v_escr is null then raise exception 'sem escritório na sessão' using errcode = '42501'; end if;
  update public.atp_incorporacoes
     set excluido_em = now(), excluido_por = coalesce(v_email, excluido_por)
   where id = p_id and escritorio_id = v_escr and excluido_em is null;
  get diagnostics v_n = row_count;
  if v_n = 0 then raise exception 'simulação % não encontrada neste escritório (ou já excluída)', p_id using errcode = 'P0002'; end if;
  return jsonb_build_object('id', p_id, 'excluida', true);
end $$;
revoke all on function public.atp_excluir_incorporacao(bigint) from public;
grant execute on function public.atp_excluir_incorporacao(bigint) to authenticated;

-- ── reviver (console/service_role; o app não chama) ──
create or replace function public.atp_z_incorporacao_reviver(p_id bigint) returns void
language sql security definer set search_path = public as $$
  update public.atp_incorporacoes set excluido_em = null, excluido_por = null where id = p_id;
$$;
revoke all on function public.atp_z_incorporacao_reviver(bigint) from public;

-- ── conferência (rode depois e guarde o resultado como CSV) ──
select 'politicas' as item, count(*)::text as valor from pg_policies where tablename = 'atp_incorporacoes'
union all select 'gatilho', count(*)::text from pg_trigger where tgrelid = 'public.atp_incorporacoes'::regclass and not tgisinternal
union all select 'rls_forcada', relforcerowsecurity::text from pg_class where oid = 'public.atp_incorporacoes'::regclass
union all select 'funcao_excluir', count(*)::text from pg_proc where proname = 'atp_excluir_incorporacao';
